{% set name = "simple-salesforce" %}
{% set version = "1.10.1" %}
{% set sha256sum = "20fd66cf40da732b9cdcb2f7160dde7bb298ef0c31702d1fdd767d1fc68cfe1b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - requests
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0

test:
  imports:
    - simple_salesforce

about:
  home: https://github.com/simple-salesforce/simple-salesforce
  dev_url: https://github.com/simple-salesforce/simple-salesforce
  description: 'A very simple Salesforce.com REST API client for Python'
  summary: 'Simple Salesforce is a basic Salesforce.com REST API client. The goal is to provide a very low-level interface to the API, returning an ordered dictionary of the API JSON response.'
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ['RECIPE_DIR'] }}/LICENSE.txt'


extra:
  recipe-maintainers:
    - mariusvniekerk
