{% set name = "simple-salesforce" %}
{% set version = "1.12.5" %}
{% set sha256sum = "ef65f72438e3b215619f6835d3d4356e147adf3a7ece6896d239127dd6aefcd1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  script: python -m pip install --no-deps --ignore-installed . --no-build-isolation
  number: 0
  skip: True  # [s390x]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python
    - requests >=2.22.0
    - cryptography
    - zeep
    - pyjwt
    - more-itertools
    - pendulum

test:
  imports:
    - simple_salesforce
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simple-salesforce/simple-salesforce
  dev_url: https://github.com/simple-salesforce/simple-salesforce
  description: 'A very simple Salesforce.com REST API client for Python'
  summary: 'Simple Salesforce is a basic Salesforce.com REST API client. The goal is to provide a very low-level interface to the API, returning an ordered dictionary of the API JSON response.'
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ['RECIPE_DIR'] }}/LICENSE.txt'
  doc_url: https://simple-salesforce.readthedocs.io/

extra:
  recipe-maintainers:
    - mariusvniekerk
