{% set name = "simple-salesforce" %}
{% set version = "1.12.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 637c9c3a3c905ff20e28a4042e47ed25b592eef19f4a97f43567928f9dfe6849

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed . --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel

  run:
    - python
    - requests >=2.22.0
    - typing-extensions
    - zeep
    - pyjwt
    - more-itertools

# > raise TypeError("auth_message must be a string")
# E TypeError: auth_message must be a string
{% set deselect_tests = " --deselect=simple_salesforce/tests/test_login.py::TestSalesforceLogin::test_connected_app_login_failure" %}
{% set deselect_tests = deselect_tests + " --deselect=simple_salesforce/tests/test_login.py::TestSalesforceLogin::test_token_login_failure" %}
test:
  source_files:
    # pyargs does not work, tests removed from site-package dir.
    - simple_salesforce
  imports:
    - simple_salesforce
  commands:
    - pip check

    - pytest -v simple_salesforce/tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - responses >=0.5.1
    - cryptography >4.0.0

about:
  home: https://github.com/simple-salesforce/simple-salesforce
  dev_url: https://github.com/simple-salesforce/simple-salesforce
  description: 'A very simple Salesforce.com REST API client for Python'
  summary: 'Simple Salesforce is a basic Salesforce.com REST API client. The goal is to provide a very low-level interface to the API, returning an ordered dictionary of the API JSON response.'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://simple-salesforce.readthedocs.io

extra:
  recipe-maintainers:
    - mariusvniekerk
