travis:
  secure:
    BINSTAR_TOKEN: nf8fa6rYhvRV63nVjG9wwxGPJxktOVGhKns2Bpr32o4TXpoB/+GZTMwsMnDJd+OFcPrSDqt+KzRDySy4EAD/D8d4Pcm3q5CNFehIwTaVhP3V2GnzWOMOOD03M87w8vps7br9CXJEcLZpZNTR/5MnB1N+ydlVX4O3tDWeDy+JafByZdr1OjhnZkYvfysvLDO+CMipIR1DldeD2lW6LSwTKa1ZuU4ldvIF70qqqHyOJVJojaOl3/uizr+AFzeKi1JpsveMXrk4sf4kpBbsSPemWPRyhG+q/BJbjfDhlZnyJCUL4WdcG9yroDXy03YJ70sVus0uDm/qaeRkMerb6I/XTzDzHaeuvkKjOM2M7I+Z4BLSu7gH+jApLHKODQ47ZBbf/hsC5Z0DuVdQJSgGXuP0nYMLc4GBpad3n2JoUd/+GJWRuabMgE8eFdZhJYNuQmd84XDd/Bb1jU0iUjZx5vxmdE80tdLciuwMBb2MFQ9YXAtgTzJS/wpL3H69Yw8CEgx/bf3DrIXIiVNVDn27JoXlz3L2sufKsmogCihWrgzE9UPmCNWYHoe46NqyuU3Vd4E9FqTwRsBBgZYtPdkPX7Dp17JC1U3XQJL3zE/FHGhpTKi1L00Qc9swa3RSsVtOvE+FEMXf/KWiCrnyZUu8THDFMiKhrd8XUQ6sSJ8LKOrRWX4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
