travis:
  secure:
    BINSTAR_TOKEN: t2MCRwuC1THT0v/DaGiH2FlZAQatis9o7hMqvLti//Jmzrrq1EMKYXMEfOYs7HsG2Ruq6ZYkOLxB0lzZ2vxCUbhH2pLRdHTZNzQZeY7+We4N7+KYzZMLmxf5WZ6faINmXynWuiXodVuSVPjRVBRgkIWpjbrUOc7dskez2jHfdbgG4Hpm3FBkensP0wVQCSgBwHfThJ8bEaTtoa2ZxkrYGeqrWevezOI1jEy7j/YqfeuGemZQos2KIrpdHUV1FulYmGDP075YcPhpdKh/LCKf9fcXC2TrJtukmloio2GZcpT5S5OVhppzZuxxM1zBhYyy36PYCVIMclhN0c8bA61UtSavWGRZvA0PVVoS0ohhf6j37UY8aK6hSKKgcdoY4mRkh7y7ONmKIX/ihE7yflTgcZMYd/Dw09SNahNpqOHpvxa6tXlmiBoVSP2mfdCt/y/1yN9RpQFw4EWTxbUmhWgDp7Sdf0xhOubMd2QkjflZcQM45FjlG/+MaB73nJysPelmY3BrNbj4pGLd+kOObTViQhRWCkZZF7rOwKor02gzRMaw2n9PsjM2F2rVTsL3zXpBnVnxUrIrfSDHMdvVSh43jG8V43MmV7W0Iwe5Em8/UstvRINfkD+irQKSjwVHwHlfbM7rCUAI1rx2V6CGMgVnpzL0DZBtUFsjq4AxyQkGiZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
